//
// Created by user on 26.05.2024.
//

#ifndef SNAKE_CASE_TO_CAMELCASE_CREATENEWFILE_H
#define SNAKE_CASE_TO_CAMELCASE_CREATENEWFILE_H


class CreateNewFile {

};


#endif //SNAKE_CASE_TO_CAMELCASE_CREATENEWFILE_H
